// src/pages/RecipeDetail.tsx
import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ChevronLeft, Heart, ExternalLink, Youtube, Clock, Users } from 'lucide-react';
import { getMealById } from '@/services/mealApi';
import { LoadingFull } from '@/components/Loading';
import { EmptyState } from '@/components/EmptyState';
import { useAppStore } from '@/store/useAppStore';
import { cn } from '@/lib/utils';
import type { Meal } from '@/types';

export function RecipeDetail() {
  const { id } = useParams<{ id: string }>();
  const [meal, setMeal] = useState<Meal | null>(null);
  const [loading, setLoading] = useState(true);
  
  const { isFavorite, addFavorite, removeFavorite } = useAppStore();
  const favorite = meal ? isFavorite(meal.idMeal) : false;

  useEffect(() => {
    const fetchMeal = async () => {
      if (!id) return;
      setLoading(true);
      try {
        const data = await getMealById(id);
        setMeal(data);
      } catch (error) {
        console.error('Failed to fetch meal:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchMeal();
  }, [id]);

  const handleFavorite = () => {
    if (!meal) return;
    if (favorite) {
      removeFavorite(meal.idMeal);
    } else {
      addFavorite(meal.idMeal);
    }
  };

  if (loading) {
    return <LoadingFull />;
  }

  if (!meal) {
    return (
      <div className="min-h-screen pb-20 md:pb-0">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-black mb-6 transition-colors"
          >
            <ChevronLeft className="w-4 h-4" />
            返回首页
          </Link>
          <EmptyState
            icon={ChevronLeft}
            title="食谱未找到"
            description="该食谱可能已被删除或不存在"
          />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen pb-20 md:pb-0">
      <div className="max-w-4xl mx-auto">
        <div className="relative">
          <img
            src={meal.strMealThumb}
            alt={meal.strMeal}
            className="w-full aspect-[16/9] md:aspect-[21/9] object-cover"
          />
          <div className="absolute top-4 left-4 right-4 flex items-center justify-between">
            <Link
              to="/"
              className="p-2 bg-white/90 hover:bg-white transition-colors"
            >
              <ChevronLeft className="w-5 h-5" />
            </Link>
            <button
              onClick={handleFavorite}
              className={cn(
                'p-2 transition-colors',
                favorite
                  ? 'bg-black text-white'
                  : 'bg-white/90 hover:bg-white'
              )}
            >
              <Heart className={cn('w-5 h-5', favorite && 'fill-current')} />
            </button>
          </div>
        </div>

        <div className="px-4 sm:px-6 lg:px-8 py-8">
          <div className="mb-6">
            <h1 className="text-2xl md:text-3xl font-bold mb-2">{meal.strMeal}</h1>
            <div className="flex items-center gap-4 text-sm text-gray-500">
              {meal.strCategory && (
                <span>{meal.strCategory}</span>
              )}
              {meal.strCategory && meal.strArea && (
                <span className="w-1 h-1 bg-gray-300 rounded-full" />
              )}
              {meal.strArea && (
                <span>{meal.strArea}</span>
              )}
            </div>
          </div>

          {meal.ingredients && meal.ingredients.length > 0 && (
            <div className="mb-8">
              <h2 className="text-lg font-medium mb-4">食材清单</h2>
              <div className="border border-gray-100">
                {meal.ingredients.map((ingredient, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between py-3 px-4 border-b border-gray-100 last:border-b-0"
                  >
                    <span className="text-sm">{ingredient.name}</span>
                    <span className="text-sm text-gray-500">{ingredient.measure}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {meal.strInstructions && (
            <div className="mb-8">
              <h2 className="text-lg font-medium mb-4">烹饪步骤</h2>
              <div className="prose prose-sm max-w-none">
                {meal.strInstructions.split('\n').filter(Boolean).map((step, index) => (
                  <p key={index} className="text-sm text-gray-600 mb-3 leading-relaxed">
                    {step}
                  </p>
                ))}
              </div>
            </div>
          )}

          <div className="flex items-center gap-4">
            {meal.strSource && (
              <a
                href={meal.strSource}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 border border-gray-200 text-sm hover:border-black transition-colors"
              >
                <ExternalLink className="w-4 h-4" />
                查看原文
              </a>
            )}
            {meal.strYoutube && (
              <a
                href={meal.strYoutube}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 bg-black text-white text-sm hover:bg-gray-800 transition-colors"
              >
                <Youtube className="w-4 h-4" />
                观看视频
              </a>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/RecipeDetail.vue
<template>
  <div class="recipe-detail">
    <div class="detail-header">
      <button class="back-btn" @click="emit('back')">
        ← 返回
      </button>
      <button class="favorite-btn" :class="{ active: isFavorite }" @click="toggleFavorite">
        <span v-if="isFavorite">★</span>
        <span v-else>☆</span>
      </button>
    </div>
    
    <div class="recipe-cover">
      <img :src="recipe.strMealThumb" :alt="recipe.strMeal">
    </div>
    
    <div class="detail-content">
      <h1 class="recipe-title">{{ recipe.strMeal }}</h1>
      
      <div class="recipe-tags">
        <span v-if="recipe.strCategory" class="tag">{{ recipe.strCategory }}</span>
        <span v-if="recipe.strArea" class="tag">{{ recipe.strArea }}</span>
      </div>
      
      <div class="detail-section" v-if="recipe.ingredients && recipe.ingredients.length > 0">
        <h3 class="section-title">所需食材</h3>
        <div class="ingredients-list">
          <div 
            v-for="(ingredient, index) in recipe.ingredients"
            :key="index"
            class="ingredient-item"
          >
            <span class="ingredient-name">{{ ingredient.name }}</span>
            <span class="ingredient-measure">{{ ingredient.measure }}</span>
          </div>
        </div>
      </div>
      
      <div class="detail-section" v-if="recipe.strInstructions">
        <h3 class="section-title">做法</h3>
        <div class="instructions">
          <p v-for="(step, index) in recipe.strInstructions.split('\n').filter(Boolean)" :key="index">
            {{ step }}
          </p>
        </div>
      </div>
      
      <div class="detail-section" v-if="recipe.strSource">
        <a 
          :href="recipe.strSource"
          target="_blank"
          rel="noopener noreferrer"
          class="source-link"
        >
          查看原文 →
        </a>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Meal } from '@/types'

defineProps<{
  recipe: Meal
  isFavorite: boolean
}>()

const emit = defineEmits<{
  back: []
  toggleFavorite: [recipe: Meal]
}>()

const toggleFavorite = () => {
  emit('toggleFavorite', props.recipe)
}

const props = defineProps<{
  recipe: Meal
  isFavorite: boolean
}>()
</script>

<style scoped>
.recipe-detail {
  background: #fff;
  min-height: 100vh;
}

.detail-header {
  position: sticky;
  top: 0;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 15px 20px;
  background: #fff;
  z-index: 10;
  border-bottom: 1px solid #e5e5e5;
}

.back-btn, .favorite-btn {
  padding: 8px 12px;
  border: 1px solid #e5e5e5;
  background: #fff;
  border-radius: 6px;
  font-size: 16px;
  cursor: pointer;
}

.favorite-btn.active {
  color: #f44336;
  border-color: #f44336;
}

.recipe-cover {
  width: 100%;
}

.recipe-cover img {
  width: 100%;
  aspect-ratio: 16/9;
  object-fit: cover;
}

.detail-content {
  padding: 20px;
}

.recipe-title {
  font-size: 24px;
  font-weight: 600;
  margin-bottom: 12px;
}

.recipe-tags {
  display: flex;
  gap: 8px;
  margin-bottom: 30px;
}

.recipe-tags .tag {
  padding: 6px 12px;
  background: #f5f5f5;
  border-radius: 15px;
  font-size: 13px;
  color: #666;
}

.detail-section {
  margin-bottom: 30px;
}

.section-title {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 15px;
  padding-bottom: 10px;
  border-bottom: 1px solid #e5e5e5;
}

.ingredients-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.ingredient-item {
  display: flex;
  justify-content: space-between;
  padding: 10px 15px;
  background: #f9f9f9;
  border-radius: 6px;
  font-size: 14px;
}

.ingredient-name {
  font-weight: 500;
}

.ingredient-measure {
  color: #666;
}

.instructions {
  line-height: 1.8;
  color: #444;
  font-size: 14px;
}

.instructions p {
  margin-bottom: 12px;
}

.source-link {
  display: inline-block;
  padding: 12px 24px;
  background: #111;
  color: #fff;
  text-decoration: none;
  border-radius: 6px;
  font-size: 14px;
}
</style>
